#开发配置
spring:
  datasource:
    url: jdbc:mysql://192.168.30.128:3306/mybatis_test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.hh.mybatisspringboot.entity
  mapperLocations: classpath:mapper/*.xml
#mybatis
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl